apiVersion: v1
kind: Service
metadata:
  name: openbao-internal
spec:
  clusterIP: None
  selector:
    app: openbao
  ports:
  - name: client
    port: 8200
    targetPort: 8200
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
spec:
  selector:
    matchLabels:
      app: openbao
  serviceName: openbao-internal
  podManagementPolicy: Parallel
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  replicas: 3
  template:
    metadata:
      labels:
        app: openbao
    spec:
      containers:
      - name: openbao
        image: ghcr.io/openbao/openbao:2.5.4
        command: ["/bin/sh", "-c", "bao server -config=/host/configs/openbao.hcl -log-level=debug"]
        ports:
        - name: client
          containerPort: 8200
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BAO_ADDR
          value: https://localhost:8200
        - name: BAO_API_ADDR
          value: https://$(POD_IP):8200
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BAO_CLUSTER_ADDR
          value: https://$(HOSTNAME).openbao-internal:8201
        - name: BAO_RAFT_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BAO_CACERT
          value: /host/certs/ca.pem
        readinessProbe:
          exec:
            command: ["/bin/sh", "-ec", "bao status -tls-skip-verify"]
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: host
          mountPath: /host
          readOnly: true
        - name: openbao-data
          mountPath: /openbao/data
          subPathExpr: $(HOSTNAME)
      volumes:
      - name: host
        hostPath:
          path: /host
          type: Directory
      - name: openbao-data
        hostPath:
          path: /openbao-volumes
          type: Directory

