log_level: "debug"

filters:
  - namespace: "default"
    pod: "openbao-*"
    container: "*"
    command: "*"
    collect:
      mountpoints:
        - "/openbao/data"
      files:
        - "/openbao/data/raft/raft.db"
        - "/openbao/data/vault.db"
