{
 "title": "OpenBao Resource Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cgroup_memory_current_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cgroup_memory_current_bytes{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(cgroup_memory_current_bytes{namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "OpenBao Resource Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage & Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "rate(cgroup_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[1m])",
     "legendFormat": "cpu.usage"
    },
    {
     "expr": "rate(cgroup_cpu_throttled_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[1m])",
     "legendFormat": "cpu.throttled"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cgroup_memory_current_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "memory.current"
    },
    {
     "expr": "cgroup_memory_peak_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "memory.peak"
    },
    {
     "expr": "cgroup_memory_high_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "memory.high"
    },
    {
     "expr": "cgroup_memory_max_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "memory.max"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_smaps_rss_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", comm=\"bao\", path=\"[anon: Go: heap]\"}) by (ns_pid)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(process_smaps_size_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", comm=\"bao\", path=\"[anon: Go: heap]\"}) by (ns_pid)",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Memory Mapped Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_smaps_rss_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", comm=\"bao\", path=~\"/openbao/data/.*\"}) by (ns_pid, path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_mountpoint_used_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "used {{mountpoint}}"
    },
    {
     "expr": "container_mountpoint_capacity_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "capacity {{mountpoint}}"
    }
   ]
  },
  {
   "title": "File Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_file_size_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "size: {{path}}"
    },
    {
     "expr": "container_file_disk_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "disk: {{path}}"
    }
   ]
  }
 ]
}