kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80 # Envoy HTTP
  - containerPort: 443
    hostPort: 443 # Envoy HTTPS
  - containerPort: 30300
    hostPort: 3000 # Grafana
  - containerPort: 30800
    hostPort: 8080 # Container Resource Exporter
  - containerPort: 30900
    hostPort: 9090 # Prometheus
  - containerPort: 30901
    hostPort: 9001 # Envoy Admin
  - containerPort: 30902
    hostPort: 9002 # Contour Metrics
  - containerPort: 30606
    hostPort: 6060 # Contour Debug (pprof, DAG)
  extraMounts:
  - hostPath: ./
    containerPath: /host
    readOnly: true
