apiVersion: v1
kind: Service
metadata:
  name: container-resource-exporter-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 8080
      nodePort: 8080
      targetPort: 8080
  selector:
    app: container-resource-exporter
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: echoserver
  namespace: default
spec:
  virtualhost:
    fqdn: echoserver.127.0.0.1.nip.io
  routes:
    - services:
        - name: echoserver
          port: 80
