apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30300
      protocol: TCP
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.3.1
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/var/lib/grafana/dashboards/envoy-details.json"
          volumeMounts:
            - name: host
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: configs/grafana-datasource.yaml
              readOnly: true
            - name: host
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: configs/grafana-dashboards.yaml
              readOnly: true
            - name: host
              mountPath: /var/lib/grafana/dashboards/envoy-details.json
              subPath: configs/grafana-envoy-details.json
              readOnly: true
      volumes:
        - name: host
          hostPath:
            path: /host
            type: Directory
